const config = {
  zh: {
    title: "数据管理平台",
    setting: "设置",
    name: "名称",
    data_name: "数据名称",
    tags_name: "标签名称",
    tags: "标签",
    data: "数据",
    description: "描述",
    data_description: "数据描述",
    create_time: "创建时间",
    id: "编号",
    action: "操作",
    add: "添加",
    edit: "编辑",
    delete: "删除",
    name_key: "请输入名称关键字",
    choose_tags: "请选择标签",
    reset: "重置",
    search: "搜索",
    input_name: "请输入数据名称",
    input_tag_name: "请输入标签名称",
    input_description: "请输入数据描述",
    ok: "提交",
    cancel: "取消",
    confirm_delete: "确认删除",
    delete_tips: "确定要删除这条数据吗？",
    data_manage: "数据管理",
    tags_manage: "标签管理",
    color: "标签颜色",
    other_error: "请求出错，请稍后重试",
    no_tag: "无标签",
    choose_tag_color: "请选择标签颜色",
  },
  en: {
    title: "Data management platform",
    setting: "Settings",
    name: "Name",
    data: "Data",
    data_name: "Data name",
    tags_name: "Tags name",
    tags: "Tags",
    description: "Description",
    data_description: "Description of data",
    create_time: "Time of creation",
    id: "ID",
    action: "Action",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    name_key: "Please enter a name keyword",
    choose_tags: "Please select tags",
    reset: "Reset",
    search: "Search",
    input_name: "Please enter a data name",
    input_tag_name: "Please enter a label name",
    input_description: "Please enter a data description",
    ok: "OK",
    cancel: "Cancel",
    confirm_delete: "Confirm",
    delete_tips: "Are you sure you want to delete this data?",
    data_manage: "Data manage",
    tags_manage: "Tags manage",
    color: "Tags Color",
    other_error: "The request failed. Please try again later！",
    no_tag: "No Tags",
    choose_tag_color: "Please select a label color",
  },
};

export default config;
